apiVersion: v1
data:
  SPLUNK_LICENSE_URI: Free
  SPLUNK_ROLE: splunk_standalone
  SPLUNK_START_ARGS: --accept-license
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: splunk-env
  namespace: splunk
