apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    app: splunk
  name: splunk2
  namespace: splunk
  annotations:
    openshift.io/scc: scc-splunk
spec:
  containers:
  - image: splunk/splunk:9.4
    name: splunk2
    envFrom:
    - secretRef:
        name: splunk-password
    - configMapRef:
        name: splunk-env
    volumeMounts:
    - mountPath: /opt/splunk/var
      name: splunk-var
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  volumes:
  - name: splunk-var
    persistentVolumeClaim:
      claimName: splunk-var
status: {}
