---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: splunk-var
  namespace: splunk
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: local-storage
  resources:
    requests:
      storage: 5Gi

# ---
# kind: PersistentVolumeClaim
# apiVersion: v1
# metadata:
#   name: splunk-etc
#   namespace: splunk
# spec:
#   accessModes:
#   - ReadWriteOnce
#   resources:
#     requests:
#       storage: 1G
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: splunk-var
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 5Gi
  local:
    path: /home/dkofler/splunk-var
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - ataltpr02
  storageClassName: local-storage

---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-storage
provisioner: kubernetes.io/no-provisioner
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer