---
apiVersion: v1
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: splunk-env
  namespace: splunk
data:
  SPLUNK_LICENSE_URI: Free
  SPLUNK_ROLE: splunk_standalone
  SPLUNK_START_ARGS: --accept-license
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: splunk-default
  namespace: splunk
data:
  default.yml: |
    splunk:
      admin_user: admin
      home: /opt/splunk
      user: splunk
      group: splunk
      hec:
        cert: null
        enable: true
        password: null
        port: 8088
        ssl: false
        token: 4b4a9dc5-5c77-4fb0-a97c-21b2bf4082fa
