kind: SecurityContextConstraints
apiVersion: security.openshift.io/v1
metadata:
  name: scc-splunk
allowPrivilegedContainer: true
runAsUser:
  type: RunAsAny
seLinuxContext:
  type: RunAsAny
fsGroup:
  type: RunAsAny
supplementalGroups:
  type: RunAsAny
users:
- splunk
groups:
- splunk