apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    app: sc4s
  name: sc4s
  namespace: sc4s
spec:
  containers:
  - image: ghcr.io/splunk/splunk-connect-for-syslog/container3:latest
    name: sc4s
    envFrom:
    - configMapRef:
        name: sc4s-env
    volumeMounts:
    - mountPath: /etc/syslog-ng/conf.d/local
      name: sc4s-etc
    - mountPath: /var/lib/syslog-ng
      name: sc4s-var
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  volumes:
  - name: sc4s-etc
    persistentVolumeClaim:
      claimName: sc4s-etc
  - name: sc4s-var
    persistentVolumeClaim:
      claimName: sc4s-var
status: {}
