---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: sc4s
  name: sc4s-syslog-tcp
  namespace: sc4s
spec:
  type: LoadBalancer
  ports:
  - name: sc4s-syslog-tcp
    port: 514
    protocol: TCP
    targetPort: 514
    nodePort: 30514
  - name: sc4s-syslog-udp
    port: 514
    protocol: UDP
    targetPort: 514
    nodePort: 30514
  selector:
    app: sc4s
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: sc4s
  name: sc4s-601-tcp
  namespace: sc4s
spec:
  ports:
  - name: sc4s-601-tcp
    port: 601
    protocol: TCP
    targetPort: 601
  selector:
    app: sc4s
  type: ClusterIP
status:
  loadBalancer: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: sc4s
  name: sc4s-6514-tcp
  namespace: sc4s
spec:
  ports:
  - name: sc4s-6514-tcp
    port: 6514
    protocol: TCP
    targetPort: 6514
  selector:
    app: sc4s
  type: ClusterIP
status:
  loadBalancer: {}